version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fitsync-postgres
    environment:
      POSTGRES_USER: fitsync
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitsync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 